### PR TITLE
Center align the todo list container

### PR DESCRIPTION
**Pull request by adnansam110**
This PR Includes the change that center aligns the container vertically.
Fixes issue #5

### CODE REVIEW

**Comment by adnansam110** [comment]
@Aryan-kumar-mains Kindly review this PR please

**Comment by Aryan-kumar-mains** [comment]
can you share screenshot before resolving the issue and after resolving the issue @adnansam110

**Comment by adnansam110** [comment]
@Aryan-kumar-mains sure

**Comment by adnansam110** [comment]
Here are the screenshots @Aryan-kumar-mains 
Before:

image

After: 

image

**Comment by adnansam110** [comment]
@Aryan-kumar-mains Kindly review it please

**Comment by adnansam110** [comment]
@Aryan-kumar-mains Kindly review this PR as well please

**Pull request merged**
